language: node_js

node_js:
  - "5.0"

addons:
  apt:
    packages:
      php5-cli
  postgresql: "9.3"

before_script:
  - make config/dbc.json build/db/create-database.sql
  - psql -U postgres <build/db/create-database.sql
  - touch .database-created
  - make

script: make run-unit-tests
