#!/bin/sh

export PGPASSWORD='nodetemplateprojectdatabasepassword'
export PGCLIENTENCODING='UTF-8'
exec psql 'nodetemplateprojectdatabase' -U 'nodetemplateprojectdatabaseuser' -h 'localhost' -p '5432' "$@"
